<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Blog;
use OpenAI\Laravel\Facades\OpenAI;

class BlogController extends Controller
{
   /* public function index()
    {
        $blogs = Blog::latest()->get();
        return view('blogs.index', compact('blogs'));
    }
*/
    //
    public function index()
{
    $blogs = \App\Models\Blog::latest()->get();
    return view('blogs.index', compact('blogs'));
}

   //
    public function generate(Request $request)
    {
        // Form Validation & Error Handling
        $request->validate([
            'title' => 'required|string|max:255|min:5',
            'keywords' => 'nullable|string|max:255',
        ]);

        try {
            $prompt = "Write a comprehensive, engaging blog post titled '" . $request->title . "'.";
            if ($request->keywords) {
                $prompt .= " Include the following keywords or themes: " . $request->keywords . ".";
            }
            $prompt .= " Format the response with clear headings using HTML tags like <h2> and <p>.";

            // OpenAI AI Feature Integration
            $result = OpenAI::chat()->create([
                'model' => 'gpt-4o-mini',
                'messages' => [
                    ['role' => 'system', 'content' => 'You are an expert blog writer.'],
                    ['role' => 'user', 'content' => $prompt],
                ],
            ]);

            $aiContent = $result->choices[0]->message->content;

            // Save to MySQL Database
            Blog::create([
                'title' => $request->title,
                'prompt_keywords' => $request->keywords,
                'content' => $aiContent,
            ]);

            return redirect()->back()->with('success', 'Blog post successfully generated by AI!');

        } catch (\Exception $e) {
            return redirect()->back()->withInput()->withErrors(['error' => 'AI Generation failed: ' . $e->getMessage()]);
        }
    }
}
